POST  https://car-marketplace-backend.vercel.app/register
content-Type: application/json

{ 
 "username":"ala",
 "address":"gtari",
 "email":"ala@gtari.tn",
 "password":"aaa",
 "phoneNumber":"28734227"
}


###

POST https://car-marketplace-backend.vercel.app/login
content-Type: application/json

{ 
 "email":"ala@gtari.tn",
 "password":"aaa"
}
###
GET https://car-marketplace-backend.vercel.app/car/630cf406e8ebf5727bc0a5f4

###
GET https://car-marketplace-backend.vercel.app/car/category/Coupe

###
GET https://car-marketplace-backend.vercel.app/car/search/p

###
GET https://car-marketplace-backend.vercel.app/car
content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYzFjYTZlYTU3MmM5YWUzZTY5YzU4IiwiZW1haWwiOiJhbGFAZ3RhcmkudG4iLCJpYXQiOjE2NjIyNDYzOTAsImV4cCI6MTY2MjI1MzU5MH0.KyOKReIraMCe09hlnNv6Y3hCG0nLMvXzni3ePP5OH_E


###
DELETE  https://car-marketplace-backend.vercel.app/car/630cf449e8ebf5727bc0a5f8
content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYzFjYTZlYTU3MmM5YWUzZTY5YzU4IiwiZW1haWwiOiJhbGFAZ3RhcmkudG4iLCJpYXQiOjE2NjIyNDYzOTAsImV4cCI6MTY2MjI1MzU5MH0.KyOKReIraMCe09hlnNv6Y3hCG0nLMvXzni3ePP5OH_E


###
POST https://car-marketplace-backend.vercel.app/car
content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYzFjYTZlYTU3MmM5YWUzZTY5YzU4IiwiZW1haWwiOiJhbGFAZ3RhcmkudG4iLCJpYXQiOjE2NjIyNDYzOTAsImV4cCI6MTY2MjI1MzU5MH0.KyOKReIraMCe09hlnNv6Y3hCG0nLMvXzni3ePP5OH_E


{
     "name": "ferrari roma",
     "price": "$250,000",
     "color": "red",
     "category": "Coupe",
     "description": "Joi.string().required()",
     "photo":"file:///var/mobile/Containers/Data/Application/70CF2220-2413-49E2-A90F-96C7E3882401/Library/Caches/ExponentExperienceData/%2540alagtari957%252FCarMarketplace/ImagePicker/A5C303CC-6141-44C9-B3EC-F9CFC7801070.png"
}

###
GET http://localhost:4000/saved
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYzFjYTZlYTU3MmM5YWUzZTY5YzU4IiwiZW1haWwiOiJhbGFAZ3RhcmkudG4iLCJpYXQiOjE2NjIyNDYzOTAsImV4cCI6MTY2MjI1MzU5MH0.KyOKReIraMCe09hlnNv6Y3hCG0nLMvXzni3ePP5OH_E

###
POST https://car-marketplace-backend.vercel.app/saved?car_id=6313da20d23862ab65f0f10d
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYzFjYTZlYTU3MmM5YWUzZTY5YzU4IiwiZW1haWwiOiJhbGFAZ3RhcmkudG4iLCJpYXQiOjE2NjIyNDYzOTAsImV4cCI6MTY2MjI1MzU5MH0.KyOKReIraMCe09hlnNv6Y3hCG0nLMvXzni3ePP5OH_E

###
PUT https://car-marketplace-backend.vercel.app/saved?car_id=6313dfb2569616920a3c91a1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYzFjYTZlYTU3MmM5YWUzZTY5YzU4IiwiZW1haWwiOiJhbGFAZ3RhcmkudG4iLCJpYXQiOjE2NjIyNDYzOTAsImV4cCI6MTY2MjI1MzU5MH0.KyOKReIraMCe09hlnNv6Y3hCG0nLMvXzni3ePP5OH_E

###
GET https://car-marketplace-backend.vercel.app/
6313e045569616920a3c91af

